print(aaaaaaaaaaaaaaaaaaaa)
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
aaaaaaaaaaaaaaaaaa
..............aaaaaa
aaaaaaaaaaaaakkkkkkkkkkkkkkkkk
............
fffffffffffffffffff/
;;;;;;lddddddddddddd
hhhhhhhhhhhhhhhhaaaaaaaaaaaaaaaa
aaaaaaaahhhhhhhhhhhhhhhh
jjjjjjjjjjjjjjjjjjjjjjddddddddddddddddddd
kkkkkkkkkkkkkkkkkkkkkkkk5555555557
((((
(((((((